/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./src/assets/models/OGanim-transformed.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/OGanim-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature004" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="GlitchCandyCreature_Body001" geometry={nodes.GlitchCandyCreature_Body001.geometry} material={materials.Body} skeleton={nodes.GlitchCandyCreature_Body001.skeleton} />
        <skinnedMesh name="GlitchCandyCreature_Head001" geometry={nodes.GlitchCandyCreature_Head001.geometry} material={materials.Head} skeleton={nodes.GlitchCandyCreature_Head001.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/OGanim-transformed.glb')
