/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 tripo1.glb --transform --draco --shadows --resolution 768 
Files: tripo1.glb [9.93MB] > /Users/radek/Documents/GIthub/GNS SITE/CreaturesSite/CreaturesSite-git and WIP/CreaturesSite/src/assets/models/tripo1-transformed.glb [1.19MB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/boss.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['tripo_node_c7370c76-670d-447e-ad20-d9fa550c239b'].geometry} material={materials['tripo_material_c7370c76-670d-447e-ad20-d9fa550c239b']} />
    </group>
  )
}

useGLTF.preload('/boss.glb')
