/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 plant1.glb --transform --draco --shadows --resolution 512 
Files: plant1.glb [187.37KB] > /Users/radek/Documents/GIthub/GNS SITE/CreaturesSite/CreaturesSite-git and WIP/CreaturesSite/src/assets/models/plant1-transformed.glb [24.58KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plant1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.w_pl17003.geometry} material={materials.Gradient} position={[5.065, -0.822, 7.03]} rotation={[-1.812, 1.396, 1.746]} scale={[18.012, 19.959, 19.443]} />
    </group>
  )
}

useGLTF.preload('/plant1-transformed.glb')
