/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 moog.glb --transform --draco --shadows --resolution 512 
Files: moog.glb [20.71MB] > /Users/radek/Documents/GIthub/GNS SITE/CreaturesSite/moog-transformed.glb [1.93MB] (91%)
Author: Kendrick Russell (https://sketchfab.com/Buce)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/moog-system-55-9abfaac8dcf34c62b25735ae013d2aeb
Title: Moog System 55
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Moog(props) {
  const { nodes, materials } = useGLTF('./models/moog-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.accessory_PlugKeys_0.geometry} material={materials.PlugKeys} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.boxbacks_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.plug1247_wires_0.geometry} material={materials.wires} rotation={[-Math.PI / 2, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('./models/moog-transformed.glb')

